#pragma once

#include "stdafx.h"
#include "stdio.h"

enum CAR_PART_ID : int
{
	CARPARTID_INVALID = -1,
	CARPARTID_BASE,
	CARPARTID_FRONT_BUMPER,
	CARPARTID_REAR_BUMPER,
	CARPARTID_LEFT_SIDE_MIRROR,
	CARPARTID_RIGHT_SIDE_MIRROR,
	CARPARTID_BODY,
	CARPARTID_WIDE_BODY,
	CARPARTID_ROOF,
	CARPARTID_TOP,
	CARPARTID_HOOD,
	CARPARTID_TRUNK,
	CARPARTID_SKIRT,
	CARPARTID_SPOILER,
	CARPARTID_ENGINE,
	CARPARTID_HEADLIGHT,
	CARPARTID_BRAKELIGHT,
	CARPARTID_DOOR_LEFT,
	CARPARTID_DOOR_RIGHT,
	CARPARTID_DOOR_PANEL_LEFT,
	CARPARTID_DOOR_PANEL_RIGHT,
	CARPARTID_DOOR_SILL_LEFT,
	CARPARTID_DOOR_SILL_RIGHT,
	CARPARTID_FENDER,
	CARPARTID_QUARTER,
	CARPARTID_HOOD_UNDER,
	CARPARTID_TRUNK_UNDER,
	CARPARTID_EXHAUST,
	CARPARTID_BRAKE,
	CARPARTID_WHEEL,
	CARPARTID_SPINNER,
	CARPARTID_WING_MIRROR,
	CARPARTID_LICENSE_PLATE,
	CARPARTID_DAMAGE_FRONT,
	CARPARTID_DAMAGE_REAR,
	CARPARTID_DAMAGE_LEFT,
	CARPARTID_DAMAGE_RIGHT,
	CARPARTID_DAMAGE_TOP,
	CARPARTID_DECAL_HOOD,
	CARPARTID_DECAL_FRONT_WINDOW,
	CARPARTID_DECAL_REAR_WINDOW,
	CARPARTID_DECAL_LEFT_DOOR,
	CARPARTID_DECAL_RIGHT_DOOR,
	CARPARTID_DECAL_LEFT_QUARTER,
	CARPARTID_DECAL_RIGHT_QUARTER,
	CARPARTID_WIDEBODY_DECAL_LEFT_DOOR,
	CARPARTID_WIDEBODY_DECAL_RIGHT_DOOR,
	CARPARTID_WIDEBODY_DECAL_LEFT_QUARTER,
	CARPARTID_WIDEBODY_DECAL_RIGHT_QUARTER,
	CARPARTID_PAINT,
	CARPARTID_VINYL_PAINT,
	CARPARTID_VINYL,
	CARPARTID_CARBON_FIBRE,
	CARPARTID_DECAL_TEXTURE,
	CARPARTID_WINDOW_TINT,
	CARPARTID_NEON,
	CARPARTID_CABIN_NEON_FRAME,
	CARPARTID_HEADLIGHT_BULB,
	CARPARTID_DOOR_STYLE,
	CARPARTID_HYDRAULICS,
	CARPARTID_NOS_PURGE,
	CARPARTID_TRUNK_AUDIO,
	CARPARTID_TRUNK_AUDIO_COMP_SMALL,
	CARPARTID_TRUNK_AUDIO_COMP_MEDIUM,
	CARPARTID_TRUNK_AUDIO_COMP_LARGE,
	CARPARTID_CUSTOM_HUD,
	CARPARTID_CUSTOM_HUD_PAINT,
	CARPARTID_CV,
	CARPARTID_WHEEL_MANUFACTURER,
	CARPARTID_MISC,
	CARPARTID_NUM = 69,
};

struct CarPartIDName
{
	CAR_PART_ID CarPartID;
	char const* Name;
};

CarPartIDName* CarPartIDNames = (CarPartIDName*)0x803338;

char const* GetCarPartIDName(int CarPartID)
{
	if (CarPartID < 0 || CarPartID >= CAR_PART_ID::CARPARTID_NUM)
		return "NONE";
	return CarPartIDNames[CarPartID].Name;
}

int GetCarPartIDFromName(char const* Name)
{
	for (int i = 0; i < CAR_PART_ID::CARPARTID_NUM; ++i)
	{
		if (strcmp(CarPartIDNames[i].Name, Name) == 0)
			return CarPartIDNames[i].CarPartID;
	}
	return CAR_PART_ID::CARPARTID_INVALID;
}