#pragma once

#include "stdafx.h"
#include "stdio.h"

enum CAR_SLOT_ID : int
{
	CARSLOTID_INVALID = -1,
	CARSLOTID_BASE,
	CARSLOTID_FRONT_BUMPER,
	CARSLOTID_REAR_BUMPER,
	CARSLOTID_LEFT_SIDE_MIRROR,
	CARSLOTID_RIGHT_SIDE_MIRROR,
	CARSLOTID_BODY,
	CARSLOTID_WIDE_BODY,
	CARSLOTID_ROOF,
	CARSLOTID_TOP,
	CARSLOTID_HOOD,
	CARSLOTID_TRUNK,
	CARSLOTID_SKIRT,
	CARSLOTID_SPOILER,
	CARSLOTID_ENGINE,
	CARSLOTID_HEADLIGHT,
	CARSLOTID_BRAKELIGHT,
	CARSLOTID_EXHAUST,
	CARSLOTID_DOOR_LEFT,
	CARSLOTID_DOOR_RIGHT,
	CARSLOTID_DOOR_PANEL_LEFT,
	CARSLOTID_DOOR_PANEL_RIGHT,
	CARSLOTID_DOOR_SILL_LEFT,
	CARSLOTID_DOOR_SILL_RIGHT,
	CARSLOTID_FENDER,
	CARSLOTID_QUARTER,
	CARSLOTID_HOOD_UNDER,
	CARSLOTID_TRUNK_UNDER,
	CARSLOTID_FRONT_BRAKE,
	CARSLOTID_REAR_BRAKE,
	CARSLOTID_FRONT_WHEEL,
	CARSLOTID_REAR_WHEEL,
	CARSLOTID_SPINNER,
	CARSLOTID_WING_MIRROR,
	CARSLOTID_LICENSE_PLATE,
	CARSLOTID_TRUNK_AUDIO,
	CARSLOTID_TRUNK_AUDIO_COMP_0,
	CARSLOTID_TRUNK_AUDIO_COMP_1,
	CARSLOTID_TRUNK_AUDIO_COMP_2,
	CARSLOTID_TRUNK_AUDIO_COMP_3,
	CARSLOTID_TRUNK_AUDIO_COMP_4,
	CARSLOTID_TRUNK_AUDIO_COMP_5,
	CARSLOTID_TRUNK_AUDIO_COMP_6,
	CARSLOTID_TRUNK_AUDIO_COMP_7,
	CARSLOTID_TRUNK_AUDIO_COMP_8,
	CARSLOTID_TRUNK_AUDIO_COMP_9,
	CARSLOTID_TRUNK_AUDIO_COMP_10,
	CARSLOTID_TRUNK_AUDIO_COMP_11,
	CARSLOTID_DAMAGE_FRONT,
	CARSLOTID_DAMAGE_REAR,
	CARSLOTID_DAMAGE_LEFT,
	CARSLOTID_DAMAGE_RIGHT,
	CARSLOTID_DAMAGE_TOP,
	CARSLOTID_DECAL_HOOD,
	CARSLOTID_DECAL_FRONT_WINDOW,
	CARSLOTID_DECAL_REAR_WINDOW,
	CARSLOTID_DECAL_LEFT_DOOR,
	CARSLOTID_DECAL_RIGHT_DOOR,
	CARSLOTID_DECAL_LEFT_QUARTER,
	CARSLOTID_DECAL_RIGHT_QUARTER,
	CARSLOTID_WIDEBODY_DECAL_LEFT_DOOR,
	CARSLOTID_WIDEBODY_DECAL_RIGHT_DOOR,
	CARSLOTID_WIDEBODY_DECAL_LEFT_QUARTER,
	CARSLOTID_WIDEBODY_DECAL_RIGHT_QUARTER,
	CARSLOTID_BASE_PAINT,
	CARSLOTID_VINYL_LAYER0,
	CARSLOTID_VINYL_LAYER1,
	CARSLOTID_VINYL_LAYER2,
	CARSLOTID_VINYL_LAYER3,
	CARSLOTID_PAINT_ENGINE,
	CARSLOTID_PAINT_SPOILER,
	CARSLOTID_PAINT_BRAKE,
	CARSLOTID_PAINT_EXHAUST,
	CARSLOTID_PAINT_AUDIO,
	CARSLOTID_PAINT_RIM,
	CARSLOTID_PAINT_SPINNER,
	CARSLOTID_PAINT_ROOF,
	CARSLOTID_PAINT_MIRROR,
	CARSLOTID_VINYL_COLOUR0_0,
	CARSLOTID_VINYL_COLOUR0_1,
	CARSLOTID_VINYL_COLOUR0_2,
	CARSLOTID_VINYL_COLOUR0_3,
	CARSLOTID_VINYL_COLOUR1_0,
	CARSLOTID_VINYL_COLOUR1_1,
	CARSLOTID_VINYL_COLOUR1_2,
	CARSLOTID_VINYL_COLOUR1_3,
	CARSLOTID_VINYL_COLOUR2_0,
	CARSLOTID_VINYL_COLOUR2_1,
	CARSLOTID_VINYL_COLOUR2_2,
	CARSLOTID_VINYL_COLOUR2_3,
	CARSLOTID_VINYL_COLOUR3_0,
	CARSLOTID_VINYL_COLOUR3_1,
	CARSLOTID_VINYL_COLOUR3_2,
	CARSLOTID_VINYL_COLOUR3_3,
	CARSLOTID_KIT_CARBON,
	CARSLOTID_HOOD_CARBON,
	CARSLOTID_DOOR_CARBON,
	CARSLOTID_TRUNK_CARBON,
	CARSLOTID_DECAL_HOOD_TEX0,
	CARSLOTID_DECAL_HOOD_TEX1,
	CARSLOTID_DECAL_HOOD_TEX2,
	CARSLOTID_DECAL_HOOD_TEX3,
	CARSLOTID_DECAL_HOOD_TEX4,
	CARSLOTID_DECAL_HOOD_TEX5,
	CARSLOTID_DECAL_HOOD_TEX6,
	CARSLOTID_DECAL_HOOD_TEX7,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX0,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX1,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX2,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX3,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX4,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX5,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX6,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX7,
	CARSLOTID_DECAL_REAR_WINDOW_TEX0,
	CARSLOTID_DECAL_REAR_WINDOW_TEX1,
	CARSLOTID_DECAL_REAR_WINDOW_TEX2,
	CARSLOTID_DECAL_REAR_WINDOW_TEX3,
	CARSLOTID_DECAL_REAR_WINDOW_TEX4,
	CARSLOTID_DECAL_REAR_WINDOW_TEX5,
	CARSLOTID_DECAL_REAR_WINDOW_TEX6,
	CARSLOTID_DECAL_REAR_WINDOW_TEX7,
	CARSLOTID_DECAL_LEFT_DOOR_TEX0,
	CARSLOTID_DECAL_LEFT_DOOR_TEX1,
	CARSLOTID_DECAL_LEFT_DOOR_TEX2,
	CARSLOTID_DECAL_LEFT_DOOR_TEX3,
	CARSLOTID_DECAL_LEFT_DOOR_TEX4,
	CARSLOTID_DECAL_LEFT_DOOR_TEX5,
	CARSLOTID_DECAL_LEFT_DOOR_TEX6,
	CARSLOTID_DECAL_LEFT_DOOR_TEX7,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX0,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX1,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX2,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX3,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX4,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX5,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX6,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX7,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX0,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX1,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX2,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX3,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX4,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX5,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX6,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX7,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX0,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX1,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX2,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX3,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX4,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX5,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX6,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX7,
	CARSLOTID_WINDOW_TINT,
	CARSLOTID_NEON,
	CARSLOTID_NEON_ENGINE,
	CARSLOTID_NEON_CABIN,
	CARSLOTID_NEON_TRUNK,
	CARSLOTID_CABIN_NEON_FRAME,
	CARSLOTID_HEADLIGHT_BULB,
	CARSLOTID_DOOR_STYLE,
	CARSLOTID_HYDRAULICS,
	CARSLOTID_NOS_PURGE,
	CARSLOTID_CUSTOM_HUD,
	CARSLOTID_HUD_BACKING_COLOUR,
	CARSLOTID_HUD_NEEDLE_COLOUR,
	CARSLOTID_HUD_CHARACTER_COLOUR,
	CARSLOTID_CV,
	CARSLOTID_WHEEL_MANUFACTURER,
	CARSLOTID_MISC,
	CARSLOTID_NUM = 170,
	CARSLOTID_MODEL_FIRST = 0,
	CARSLOTID_MODEL_LAST = 62,
	CARSLOTID_MODEL_NUM = 63,
	CARSLOTID_FIRST_NONRENDER = 63,
	CARSLOTID_LAST_NONRENDER = 169,
	CARSLOTID_NONRENDER_NUM = 107,
	CARSLOTID_ATTACHMENT_MODEL_FIRST = 47,
	CARSLOTID_ATTACHMENT_MODEL_LAST = 51,
	CARSLOTID_ATTACHMENT_MODEL_NUM = 5,
	CARSLOTID_DECAL_MODEL_FIRST = 52,
	CARSLOTID_DECAL_MODEL_LAST = 58,
	CARSLOTID_DECAL_MODEL_NUM = 7,
};

struct CarSlotIDName
{
	CAR_SLOT_ID CarSlotID;
	char const* Name;
};

CarSlotIDName* CarSlotIDNames = (CarSlotIDName*)0x802DE8;
int *CarPartSlotMap = (int*)0x802960;

char const* GetCarSlotIDName(int CarSlotID)
{
	if (CarSlotID >= 0x40302010) // Animations (to use with CameraInfo)
	{
		switch (CarSlotID)
		{
		case 0x40302010: default: return "ANIM0";
		case 0x40302011: return "ANIM1";
		case 0x40302012: return "ANIM2";
		case 0x40302013: return "ANIM3";
		case 0x40302014: return "ANIM4";
		case 0x40302015: return "ANIM5";
		case 0x40302016: return "ANIM6";
		}
	}

	if (CarSlotID < 0 || CarSlotID >= CARSLOTID_NUM)
		return "NONE";
	return CarSlotIDNames[CarSlotID].Name;
}

int GetCarSlotIDFromName(char const* Name)
{
	for (int i = 0; i < CARSLOTID_NUM; ++i)
	{
		if (strcmp(CarSlotIDNames[i].Name, Name) == 0)
			return CarSlotIDNames[i].CarSlotID;
	}
	return CARSLOTID_INVALID;
}

int GetCarPartFromSlot(int CarSlotID)
{
	if (CarSlotID < 0 || CarSlotID >= CARSLOTID_NUM)
		return -1;
	return CarPartSlotMap[CarSlotID];
}

int GetCarSlotIDFromPart(int CarPartID)
{
	for (int i = 0; i < CARSLOTID_NUM; ++i)
	{
		if (CarPartSlotMap[i] == CarPartID)
			return i;
	}
	return CARSLOTID_INVALID;
}

int ExtraAttachmentSlots[6] = {
			CARSLOTID_DOOR_PANEL_LEFT, CARSLOTID_DOOR_PANEL_RIGHT,
			CARSLOTID_DOOR_SILL_LEFT,  CARSLOTID_DOOR_SILL_RIGHT,
			CARSLOTID_HOOD_UNDER,      CARSLOTID_TRUNK_UNDER,
};